-- Seed data for IELTS topics
USE ielts_data;

-- Writing Topics (Task 1)
INSERT INTO writing_topics (task_type, title, chart_type, chart_description, category, difficulty) VALUES
(1, 'The chart below shows the percentage of households in owned and rented accommodation in England and Wales between 1918 and 2011.', 'bar', 'A bar chart comparing owned vs rented accommodation percentages across decades from 1918 to 2011.', 'housing', 3),
(1, 'The graph below shows the quantities of goods transported in the UK between 1974 and 2002 by four different modes of transport.', 'line', 'A line graph showing goods transported by road, water, rail, and pipeline from 1974 to 2002 in million tonnes.', 'transport', 3),
(1, 'The pie charts below show the comparison of different kinds of energy production of France in two years.', 'pie', 'Two pie charts comparing energy production sources (nuclear, thermal, hydroelectric, other) in 1995 and 2005.', 'energy', 2),
(1, 'The table below gives information about the underground railway systems in six cities.', 'table', 'A table showing date opened, kilometres of route, and passengers per year for London, Paris, Tokyo, Washington DC, Kyoto, and Los Angeles metro systems.', 'infrastructure', 2),
(1, 'The maps below show the centre of a small town called Islip as it is now, and plans for its development.', 'map', 'Two maps showing the current layout of Islip town centre and proposed redevelopment plans including new housing, shops, and a dual carriageway.', 'urban_planning', 4);

-- Writing Topics (Task 2)
INSERT INTO writing_topics (task_type, title, chart_type, chart_description, category, difficulty) VALUES
(2, 'Some people think that clean water should be provided free of charge to everyone. Others think that this is not a sustainable solution. Discuss both views and give your opinion.', NULL, NULL, 'government', NULL),
(2, 'In many countries, schools have long summer holidays. Some people think shorter holidays would be more beneficial. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Some people think that reducing air travel is the best way to protect the environment. Others believe the disadvantages for individuals and businesses outweigh the environmental benefits. Discuss both views and give your opinion.', NULL, NULL, 'environment', NULL),
(2, 'Global fashion trends have a significant impact on the way people dress. Why is this happening? Do you think it is a positive or negative development?', NULL, NULL, 'culture', NULL),
(2, 'Some people think that a sense of competition should be encouraged in work and school. Others believe that we should focus more on teamwork and cooperation. Discuss both views and give your opinion.', NULL, NULL, 'social life', NULL),
(2, 'Some people think that the standard workweek should be reduced and weekends extended. To what extent do you agree or disagree?', NULL, NULL, 'social life', NULL),
(2, 'It is important for young people to learn how to save money from an early age. To what extent do you agree or disagree?', NULL, NULL, 'social life', NULL),
(2, 'Nowadays, a wide variety of international food is available in local supermarkets. Is this a positive or negative development?', NULL, NULL, 'urbanization & globalization', NULL),
(2, 'The main aim of science should be to improve people''s lives. To what extent do you agree or disagree?', NULL, NULL, 'media & technology', NULL),
(2, 'Some people think that university students should study a wide range of subjects. Others think they should only focus on their main subject. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'In the future, the majority of the global population will live in urban areas. Is this a positive or negative development?', NULL, NULL, 'urbanization & globalization', NULL),
(2, 'In many countries, the proportion of older people is steadily increasing. Does this trend have more positive or negative effects on society?', NULL, NULL, 'government', NULL),
(2, 'Taking risks brings many benefits to both our personal and professional lives. Do the advantages of taking risks outweigh the disadvantages?', NULL, NULL, 'abstract', NULL),
(2, 'Nowadays, young people are spending an increasing amount of time on their smartphones. Why is this the case? Is it a positive or negative development?', NULL, NULL, 'education', NULL),
(2, 'Some people believe that professionals should remain and work in the country where they were trained. Others believe they should be free to work in another country. Discuss both views and give your opinion.', NULL, NULL, 'social life', NULL),
(2, 'An increasing number of people are choosing alternative medicine over conventional treatments. Do the advantages of this development outweigh the disadvantages?', NULL, NULL, 'social life', NULL),
(2, 'In some countries, more and more people are becoming interested in finding out about the history of the house or building they live in. What are the reasons for this? How can people research this?', NULL, NULL, 'education', NULL),
(2, 'Nowadays, many companies market their products by emphasizing how new or updated they are. Why is this the case? Is this a positive or negative development?', NULL, NULL, 'media & technology', NULL),
(2, 'High levels of sugar are contained in many manufactured foods, causing health problems. Some people think the best way to solve this is to make sugary products more expensive. To what extent do you agree or disagree?', NULL, NULL, 'social life', NULL),
(2, 'In the future, advanced self-driving technology will make human drivers unnecessary. Will this have a positive or negative impact on society?', NULL, NULL, 'media & technology', NULL),
(2, 'In some countries, owning a home is considered more important than renting one. Why is this the case? Is this a positive or negative situation?', NULL, NULL, 'social life', NULL),
(2, 'Some people believe that printed books are no longer necessary in the digital era because all reading can be done online. To what extent do you agree or disagree?', NULL, NULL, 'media & technology', NULL),
(2, 'The widespread use of advertisements means they are no longer effective at catching consumers'' attention. To what extent do you agree or disagree?', NULL, NULL, 'media & technology', NULL),
(2, 'In some cultures, parents teach their children that if they try hard enough, they can achieve anything. What are the advantages and disadvantages of this approach?', NULL, NULL, 'education', NULL),
(2, 'Some people believe that it is best to accept a bad situation, such as an unsatisfactory job or shortage of money. Others argue that it is better to try and improve such situations. Discuss both views and give your opinion.', NULL, NULL, 'social life', NULL),
(2, 'Some people consider the loss of individual species of plants and animals to be the main environmental problem of our time. Others believe that there are more important environmental issues. Discuss both views and give your opinion.', NULL, NULL, 'environment', NULL),
(2, 'Some people believe that music is a good way of bringing people of different cultures and ages together. To what extent do you agree or disagree?', NULL, NULL, 'social life', NULL),
(2, 'Many people prefer to be self-employed rather than working for a company. Why might this be the case? What are the drawbacks of being self-employed?', NULL, NULL, 'social life', NULL),
(2, 'Living in a country where you have to speak a foreign language can cause serious social and practical problems. To what extent do you agree or disagree?', NULL, NULL, 'social life', NULL),
(2, 'Nowadays, people have too many choices. To what extent do you agree or disagree?', NULL, NULL, 'abstract', NULL),
(2, 'Some people think that history is one of the most important school subjects. Other people think that, in today''s world, subjects like science and technology are more important. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Despite advancements in agriculture technology, famine remains a severe problem in many parts of the world. What are the causes of this issue, and what measures can be taken to solve it?', NULL, NULL, 'social life', NULL),
(2, 'Some people believe that nations should share valuable information and research with each other. Others believe that countries should keep this information secret. Discuss both views and give your opinion.', NULL, NULL, 'media & technology', NULL),
(2, 'In many countries, the population is becoming younger. Do you think the advantages of this trend outweigh the disadvantages?', NULL, NULL, 'social life', NULL),
(2, 'Some people think that governments should invest more in high-speed rail networks between cities. Others think that upgrading existing public transport systems should be the priority. Discuss both views and give your opinion.', NULL, NULL, 'government', NULL),
(2, 'Some people think that children should be encouraged to make decisions about their daily lives. Others think they should rely on their parents to make decisions for them. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Some people think that governments should spend money on railways rather than roads. To what extent do you agree or disagree?', NULL, NULL, 'government', NULL),
(2, 'Some people think that the government should make laws to force people to recycle their household waste. To what extent do you agree or disagree?', NULL, NULL, 'environment', NULL),
(2, 'Some people believe that the only reason to learn a foreign language is to travel or work in a foreign country. Others think that these are not the only reasons. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Many governments think that economic progress is their most important goal. Some people, however, think that other types of progress are equally important. Discuss both views and give your opinion.', NULL, NULL, 'government', NULL),
(2, 'It is important for children to learn the difference between right and wrong at an early age. Punishment is necessary to help them learn this distinction. To what extent do you agree or disagree?', NULL, NULL, 'education', NULL),
(2, 'Some people think that university students should only study subjects that will be useful in the future. Others think that university students should be allowed to study whatever they like. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Countries are becoming increasingly similar because people are able to buy the same products anywhere in the world. Do you think this is a positive or negative development?', NULL, NULL, 'social life', NULL),
(2, 'Some museums charge an admission fee, while others are free. Do you think the advantages of charging admission outweigh the disadvantages?', NULL, NULL, 'social life', NULL),
(2, 'Some experts believe that it is better for children to begin learning a foreign language at primary school rather than secondary school. Do the advantages of this outweigh the disadvantages?', NULL, NULL, 'education', NULL),
(2, 'Some people think that unpaid community service should be a compulsory part of high school programs. To what extent do you agree or disagree?', NULL, NULL, 'education', NULL),
(2, 'Some people think that the best way to improve public health is by increasing the number of sports facilities. Others, however, say that this would have little effect on public health and that other measures are required. Discuss both views and give your opinion.', NULL, NULL, 'social life', NULL),
(2, 'Every year several languages die out. Some people think that this is not important because life will be easier if there are fewer languages in the world. To what extent do you agree or disagree?', NULL, NULL, 'culture', NULL),
(2, 'Parents should be the ones to teach their children how to be good members of society. Others believe that school is the best place to learn this. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'The development of technology has changed the way people interact with each other. In what ways has technology changed the types of relationships people make? Is this a positive or negative development?', NULL, NULL, 'media & technology', NULL),
(2, 'Increasing the price of petrol is the best way to solve growing traffic and pollution problems. To what extent do you agree or disagree?', NULL, NULL, 'environment', NULL),
(2, 'In many countries, an increasing number of people are suffering from health problems linked to poor diet and lifestyle. What are the causes of this? What solutions can you suggest?', NULL, NULL, 'social life', NULL),
(2, 'It is generally believed that some people are born with certain talents, for instance for sport or music, and others are not. However, it is sometimes claimed that any child can be taught to become a good sports person or musician. Discuss both these views and give your own opinion.', NULL, NULL, 'education', NULL),
(2, 'Some people believe that there should be fixed punishments for each type of crime. Others, however, argue that the circumstances of an individual crime, and the motivation for committing it, should always be taken into account when deciding on the punishment. Discuss both these views and give your own opinion.', NULL, NULL, 'crime', NULL),
(2, 'As most people spend a major part of their adult life at work, job satisfaction is an important element of individual wellbeing. What factors contribute to job satisfaction? How realistic is the expectation of job satisfaction for all workers?', NULL, NULL, 'social life', NULL),
(2, 'Some people think that the main purpose of a university education is to help students find better jobs. Others think that a university education has wider benefits for individuals and society. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Today, the high sales of popular consumer goods reflect the power of advertising and not the real needs of the society in which they are sold. To what extent do you agree or disagree?', NULL, NULL, 'media & technology', NULL),
(2, 'Successful sports professionals can earn a great deal more money than people in other important professions. Some people think this is fully justified while others think it is unfair. Discuss both these views and give your own opinion.', NULL, NULL, 'social life', NULL),
(2, 'When people travel to a different country, they should adapt to the local customs and traditions. To what extent do you agree or disagree?', NULL, NULL, 'social life', NULL),
(2, 'Some people prefer to spend their lives doing the same things and avoiding change. Others, however, think that change is always a good thing. Discuss both views and give your opinion.', NULL, NULL, 'social life', NULL),
(2, 'Universities should accept equal numbers of male and female students in every subject. To what extent do you agree or disagree?', NULL, NULL, 'education', NULL),
(2, 'In some countries, young people are encouraged to work or travel for a year between finishing high school and starting university studies. Discuss the advantages and disadvantages for young people who decide to do this.', NULL, NULL, 'education', NULL),
(2, 'Some people think that a sense of competition in children should be encouraged. Others believe that children who are taught to co-operate rather than compete become more useful adults. Discuss both views and give your opinion.', NULL, NULL, 'education', NULL),
(2, 'Research indicates that the characteristics we are born with have much more influence on our personality and development than any experiences we may have in our life. Which do you consider to be the major influence?', NULL, NULL, 'social life', NULL),
(2, 'Books, movies, television, and radio are all ways of communicating information. Which do you think is the most effective?', NULL, NULL, 'social life', NULL),
(2, 'Happiness is considered very important in life. Why is it difficult to define? What factors are important in achieving happiness?', NULL, NULL, 'social life', NULL),
(2, 'Some people think that the government should control or censor the media and creative arts. Others think that artists and the media should be free to produce whatever they want. Discuss both views and give your opinion.', NULL, NULL, 'government', NULL),
(2, 'In many countries, schools have severe problems with student behaviour. What do you think are the causes of this? What solutions can you suggest?', NULL, NULL, 'education', NULL);

-- Speaking Topics (Part 1)
INSERT INTO speaking_topics (part, question, cue_card, follow_up_questions, category, season) VALUES
(1, 'Do you work or are you a student?', NULL, NULL, 'work_study', '2024S1'),
(1, 'What do you like about your job/studies?', NULL, NULL, 'work_study', '2024S1'),
(1, 'Do you live in a house or an apartment?', NULL, NULL, 'accommodation', '2024S1'),
(1, 'What is your favourite room in your home?', NULL, NULL, 'accommodation', '2024S1'),
(1, 'How often do you use the internet?', NULL, NULL, 'technology', '2024S1'),
(1, 'What do you usually do on the internet?', NULL, NULL, 'technology', '2024S1'),
(1, 'Do you like reading books? What kind of books do you like?', NULL, NULL, 'hobbies', '2024S1'),
(1, 'How do you usually spend your weekends?', NULL, NULL, 'leisure', '2024S1'),
(1, 'Do you prefer to travel alone or with friends?', NULL, NULL, 'travel', '2024S1'),
(1, 'What kind of weather do you like?', NULL, NULL, 'weather', '2024S1');

-- Speaking Topics (Part 2)
INSERT INTO speaking_topics (part, question, cue_card, follow_up_questions, category, season) VALUES
(2, 'Describe a book that you have read recently.',
 'You should say:\n- what the book was about\n- why you decided to read it\n- what you liked or disliked about it\nand explain whether you would recommend it to others.',
 '["Do you often read books?", "What types of books are popular in your country?", "Do you think reading is important? Why?"]',
 'hobbies', '2024S1'),
(2, 'Describe a place you have visited that you particularly liked.',
 'You should say:\n- where it was\n- when you went there\n- what you did there\nand explain why you liked it so much.',
 '["Do you like travelling?", "What kind of places do you prefer to visit?", "Do you think tourism is good for local communities?"]',
 'travel', '2024S1'),
(2, 'Describe a person who has had a great influence on you.',
 'You should say:\n- who this person is\n- how you know this person\n- what this person has done to influence you\nand explain why they have had such a great influence.',
 '["Who influences young people more, parents or friends?", "Do you think famous people are good role models?", "Has the influence of teachers changed over time?"]',
 'people', '2024S1'),
(2, 'Describe a skill that took you a long time to learn.',
 'You should say:\n- what the skill was\n- when you started learning it\n- why it took so long to learn\nand explain how you felt when you finally mastered it.',
 '["What skills are important for young people to learn?", "Do you think schools teach enough practical skills?", "Is it better to learn skills online or in person?"]',
 'education', '2024S1'),
(2, 'Describe a time when you helped someone.',
 'You should say:\n- who you helped\n- how you helped them\n- why you helped them\nand explain how you felt about helping them.',
 '["Do you think people help each other more now than in the past?", "Why do some people volunteer?", "Should schools teach children to help others?"]',
 'society', '2024S1');

-- Speaking Topics (Part 3)
INSERT INTO speaking_topics (part, question, cue_card, follow_up_questions, category, season) VALUES
(3, 'What are the advantages and disadvantages of reading e-books compared to paper books?', NULL,
 '["Do you think paper books will disappear in the future?", "How has technology changed the way people read?", "Should governments do more to encourage reading?"]',
 'hobbies', '2024S1'),
(3, 'How has tourism changed in your country over the past few decades?', NULL,
 '["What are the negative effects of tourism on the environment?", "Should there be limits on the number of tourists visiting certain places?", "How can tourism be made more sustainable?"]',
 'travel', '2024S1'),
(3, 'Do you think the education system in your country prepares students well for work?', NULL,
 '["What changes would you make to the education system?", "Is university education necessary for success?", "How will education change in the next 20 years?"]',
 'education', '2024S1'),
(3, 'Some people say that we should spend money on exploring outer space. Others disagree. What is your opinion?', NULL,
 '["What are the practical benefits of space exploration?", "Should space exploration be funded by governments or private companies?", "Do you think humans will live on other planets in the future?"]',
 'science', '2024S1'),
(3, 'In what ways can governments encourage people to live healthier lifestyles?', NULL,
 '["Should unhealthy food be taxed more heavily?", "Is it the responsibility of individuals or governments to ensure people are healthy?", "How has the concept of a healthy lifestyle changed over time?"]',
 'health', '2024S1');
